apiVersion: v1
kind: Service
metadata:
  name: demoapp
  labels:
    app: demoapp
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: demoapp
  type: ClusterIP