apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  labels:
    app: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: idriss1704/demoapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "0.2"
            memory: 300Mi
          limits:
            cpu: "1.0"
            memory: 300Mi
